const WORLD = {
    WALL_LEFT: '||',
    WALL_RIGHT: '|',
    WALL_TOP: '‾',
    WALL_BOTTOM: '_',
    WALL_TOPLEFTCORNER: '⌜',
    WALL_TOPRIGHTCORNER: '⌝',
    WALL_BOTTOMLEFTCORNER: '⌞',
    WALL_BOTTOMRIGHTCORNER: '⌟',
    GROUND: '□'
}
